spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BookHub;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=secret
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.context-path=/api

# ===== Configuration email (DEV - MailHog) =====
# http://localhost:8025
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Identité
bookhub.mail.from=no-reply@bookhub-dev.local
bookhub.mail.from-name=BookHub (DEV)
