spring.datasource.url=jdbc:sqlserver://localhost:1434;databaseName=bookhub_prod;encrypt=false
spring.datasource.username=sa
spring.datasource.password=secret

server.servlet.context-path=/api

jwt.secret=${JWT_SECRET}

# ===== Configuration email (PROD & Brevo) =====
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_SMTP_USER}
spring.mail.password=${BREVO_SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Identité
bookhub.mail.from=contact@quartier-solidaire.fr
bookhub.mail.from-name=Bibliothèque Quartier Solidaire
